-- AlterTable
ALTER TABLE `businesscategory` MODIFY `status` ENUM('ACTIVE', 'INACTIVE', 'DETAILS_SUBMISSION_INCOMPLETE', 'DETAILS_SUBMISSION_COMPLETED', 'REJECTED') NOT NULL DEFAULT 'ACTIVE';

-- AlterTable
ALTER TABLE `vendor` MODIFY `status` ENUM('ACTIVE', 'INACTIVE', 'DETAILS_SUBMISSION_INCOMPLETE', 'DETAILS_SUBMISSION_COMPLETED', 'REJECTED') NOT NULL DEFAULT 'ACTIVE';
